language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET=all
  - TARGET=test

addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libjack-jackd2-dev
      - portaudio19-dev
      - libfftw3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install gtk+;
      brew install portaudio;
      brew install fftw;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET" == "test" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

script:
  make "$TARGET"
